[package]
name = "encrypted-communication"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
derive = "1.0.0"
rand = "0.8.5"
rsa = {version = "0.9.6", features = ["sha2"]}
serde = { version="1.0.210", features = ["derive"]}
serde_json = "1.0.128"
typenum = "1.19.0"
